name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "15 */3 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |-
        python build_profile.py
        cat README.md
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        git config --local user.email "yzz0225@auburn.edu"
        git config --local user.name "Yimin Zhong"
        git add README.md
        git commit -m "Update README" || echo "No changes to commit"
        git push
